### ISSUE TITLE
BUG: Cannot create release notes

### ISSUE THREAD

**Issue by prjemian** [prjemian/murky#19]
```bash
(murky) prjemian@arf:~/.../BCDA-APS/apstools$ create_release_notes --head main 1.6.17 1.6.18 ack! | tee /tmp/notes.md
Traceback (most recent call last):
  File "/home/prjemian/.conda/envs/murky/bin/create_release_notes", line 11, in <module>
    sys.exit(main())
  File "/home/prjemian/.conda/envs/murky/lib/python3.10/site-packages/murky/create_release_notes.py", line 300, in main
    info = get_release_info(token, base_tag_name, head_branch_name, milestone_name)
  File "/home/prjemian/.conda/envs/murky/lib/python3.10/site-packages/murky/create_release_notes.py", line 129, in get_release_info
    pulls = {
  File "/home/prjemian/.conda/envs/murky/lib/python3.10/site-packages/murky/create_release_notes.py", line 130, in <dictcomp>
    p.number: p for p in repo.get_pulls(state="closed") if p.closed_at > earliest
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by prjemian** [comment]
The error happens when `earliest` is `None` which should not be happening.
There is an update to the pygithub package:

```
  pygithub                               2.1.1-pyhd8ed1ab_0 --> 2.2.0-pyhd8ed1ab_0 
```
