### ISSUE TITLE
CI cannot upload to coveralls

### ISSUE THREAD

**Issue by prjemian** [prjemian/murky#28]
```py
2024-02-10T17:15:21.8888688Z List of packages in environment: "/home/runner/micromamba-root/envs/anaconda-test-env-py-3.9"
2024-02-10T17:15:21.8889451Z 
2024-02-10T17:15:21.8889831Z   Name       Version  Build  Channel    
2024-02-10T17:15:21.8890824Z ──────────────────────────────────────────
2024-02-10T17:15:21.8891824Z   coveralls  1.8.0    py_0   conda-forge
2024-02-10T17:15:21.8911540Z /home/runner/micromamba-root/envs/anaconda-test-env-py-3.9/bin/coveralls
2024-02-10T17:15:22.0064075Z Traceback (most recent call last):
2024-02-10T17:15:22.0066030Z   File "/home/runner/micromamba-root/envs/anaconda-test-env-py-3.9/bin/coveralls", line 6, in <module>
2024-02-10T17:15:22.0067234Z     from coveralls.cli import main
2024-02-10T17:15:22.0068954Z   File "/home/runner/micromamba-root/envs/anaconda-test-env-py-3.9/lib/python3.9/site-packages/coveralls/__init__.py", line 2, in <module>
2024-02-10T17:15:22.0070394Z     from .api import Coveralls
2024-02-10T17:15:22.0071942Z   File "/home/runner/micromamba-root/envs/anaconda-test-env-py-3.9/lib/python3.9/site-packages/coveralls/api.py", line 13, in <module>
2024-02-10T17:15:22.0073902Z     from .reporter import CoverallReporter
2024-02-10T17:15:22.0075630Z   File "/home/runner/micromamba-root/envs/anaconda-test-env-py-3.9/lib/python3.9/site-packages/coveralls/reporter.py", line 10, in <module>
2024-02-10T17:15:22.0077228Z     from coverage.report import Reporter
2024-02-10T17:15:22.0079409Z ImportError: cannot import name 'Reporter' from 'coverage.report' (/home/runner/micromamba-root/envs/anaconda-test-env-py-3.9/lib/python3.9/site-packages/coverage/report.py)
2024-02-10T17:15:22.0198515Z ##[error]Process completed with exit code 1.
2024-02-10T17:15:22.0269398Z Post job cleanup.
```

**Comment by prjemian** [comment]
Such as [punx](https://github.com/prjemian/punx/issues/189).  [Fixed](https://github.com/prjemian/punx/pull/190).

**Comment by prjemian** [comment]
577cad7

**Comment by prjemian** [comment]
from CI:

```
Warning: Unexpected input(s) 'channel-priority', 'extra-specs', valid inputs are ['condarc-file', 'condarc', 'environment-file', 'environment-name', 'create-args', 'log-level', 'micromamba-version', 'micromamba-url', 'download-micromamba', 'init-shell', 'generate-run-shell', 'cache-downloads', 'cache-downloads-key', 'cache-environment', 'cache-environment-key', 'post-cleanup', 'micromamba-root-path', 'micromamba-binary-path']
```

**Comment by prjemian** [comment]
[Force install coveralls by pip](https://github.com/z4r/python-coveralls/issues/74#issuecomment-582170116).  That worked!
